### ISSUE TITLE
選択範囲にテキストがある状態で実行した時に意図しない動作になります

### ISSUE THREAD

**Issue by novita** [tomoki1207/vscode-input-sequence#1]
例えば以下のテキストがあって、連番の箇所を100から始まる連番に修正したい場合等で、1〜5をマルチ選択していたとします。

```
xxx-1
xxx-2
xxx-3
xxx-4
xxx-5
```

その状態でコマンドを実行した際に、各々の選択範囲の内容が置き換わらずに、追加されて、以下のような状態になってしまいます。

```
xxx-1100
xxx-2101
xxx-3102
xxx-4103
xxx-5104
```

選択範囲にテキストがある場合は、生成された連番で置換動作されるように修正していただけるとうれしいです。

**Comment by tomoki1207** [comment]
使っていただきありがとうございます
実は`ctrl+shift+L`で選択してそのまま、みたいなことを思った動きだったわけですが、
おっしゃるように置換したいときには不便ですね
選択中の文字たちが全て同じ場合は
現行の挙動にしようかと思いましたが、いかがでしょう？

**Comment by novita** [comment]
お返事ありがとうございます。
実はAtomではsequential-numberを使用していて、最近VSCに乗り換えをしているところです。
Atomでのsequential-numberの挙動では選択範囲がある場合は置換動作になっていましたので、リクエストをお願いしてみました。

当方がユースケースでは、例えばCSSで以下のようなコードを行複製し、連番を振り直す様なことが多々あります。

```css
.mt1 {
  margin-top: 10px !important;
}
```

上記のコードを`.mt10`まで複製したい場合、
`.mt1`をマルチ選択し、1の部分にのみ選択された状態にします。
連番生成コマンドを実行し、`.mt1`〜`.mt10`に置換します。
`10px`をマルチ選択し、10の部分にのみ選択された状態にします。
連番生成コマンドを実行し、`10px`〜`100px`に置換します。

その際に、実際にはマルチ選択の選択内容は同一になりますので、選択範囲があった場合は生成された連番で置換の動作のほうが望ましいです。
ご検討ください。

よろしくお願いいたします。

**Comment by tomoki1207** [comment]
使う方によって置換/結合は選べた方がよさそうな感じでしたので
設定にて切り替えられるようにしました。
ご確認ください 😄

**Comment by novita** [comment]
ありがとうございました。
バッチリです！
